spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: capg123
    driver-class-name: org.postgresql.Driver
